# Generated by Django 4.2.24 on 2025-09-11 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('IDLE', 'Idle'), ('REGISTERING', 'Registration Flow'), ('BROWSING_LISTINGS', 'Browsing Listings'), ('CREATING_LISTING', 'Creating Listing'), ('PURCHASING', 'Purchase Flow'), ('TRANSFER_GUIDE', 'Transfer Guide'), ('DISPUTE', 'Dispute Flow')], default='IDLE', max_length=20)),
                ('session_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escrow.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='BotNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('TRANSFER_REMINDER', 'Transfer Reminder'), ('VERIFICATION_COMPLETE', 'Verification Complete'), ('DISPUTE_UPDATE', 'Dispute Update'), ('SYSTEM_ALERT', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('send_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='escrow.telegramuser')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escrow.escrowtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('INCOMING', 'User to Bot'), ('OUTGOING', 'Bot to User'), ('COMMAND', 'Bot Command'), ('CALLBACK', 'Callback Query')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('command', models.CharField(blank=True, max_length=50, null=True)),
                ('callback_data', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_messages', to='escrow.telegramuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
