# Generated by Django 4.2.24 on 2025-09-11 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.BigIntegerField(unique=True)),
                ('group_username', models.CharField(blank=True, max_length=100, null=True)),
                ('group_title', models.CharField(max_length=200)),
                ('group_description', models.TextField(blank=True)),
                ('member_count', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('TRADING', 'Trading'), ('TECH', 'Technology'), ('BUSINESS', 'Business'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('pinned_message', models.TextField(blank=True)),
                ('admin_list_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('bot_is_admin', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_listings', to='escrow.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='GroupVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PENDING', 'Verification Pending'), ('PASSED', 'Verification Passed'), ('FAILED', 'Verification Failed'), ('MANUAL_REVIEW', 'Requires Manual Review')], default='PENDING', max_length=20)),
                ('ownership_verified', models.BooleanField(default=False)),
                ('metadata_matches', models.BooleanField(default=False)),
                ('admin_permissions_correct', models.BooleanField(default=False)),
                ('verification_details', models.JSONField(default=dict)),
                ('failure_reasons', models.JSONField(default=list)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='escrow.escrowtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BUYER_ADDED', 'Buyer Added to Group'), ('BUYER_PROMOTED', 'Buyer Promoted to Admin'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('SELLER_LEFT', 'Seller Left Group'), ('VERIFICATION_COMPLETED', 'Verification Completed')], max_length=30)),
                ('old_owner_id', models.BigIntegerField(blank=True, null=True)),
                ('new_owner_id', models.BigIntegerField(blank=True, null=True)),
                ('admin_changes', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='escrow.escrowtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMetadataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('LISTING_CREATED', 'Listing Created'), ('PRE_TRANSFER', 'Pre Transfer'), ('POST_TRANSFER', 'Post Transfer'), ('VERIFICATION', 'Verification Check')], max_length=20)),
                ('group_title', models.CharField(max_length=200)),
                ('group_username', models.CharField(blank=True, max_length=100, null=True)),
                ('group_description', models.TextField(blank=True)),
                ('member_count', models.IntegerField()),
                ('admin_list', models.JSONField(default=list)),
                ('creator_id', models.BigIntegerField(blank=True, null=True)),
                ('pinned_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_snapshots', to='groups.grouplisting')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escrow.escrowtransaction')),
            ],
        ),
    ]
