# Generated by Django 4.2.24 on 2025-09-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member_count', models.IntegerField(default=0)),
                ('public_link', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description_hash', models.CharField(max_length=64)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='groups.grouplisting')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user_id', models.BigIntegerField()),
                ('admin_username', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('added', 'Admin Added'), ('removed', 'Admin Removed')], max_length=50)),
                ('performed_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_changes', to='groups.grouplisting')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
