# Generated by Django 4.2.24 on 2025-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupstatelog_adminchangelog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grouplisting',
            index=models.Index(fields=['status', '-created_at'], name='groups_grou_status_49d168_idx'),
        ),
        migrations.AddIndex(
            model_name='grouplisting',
            index=models.Index(fields=['seller', 'status'], name='groups_grou_seller__67755f_idx'),
        ),
        migrations.AddIndex(
            model_name='grouplisting',
            index=models.Index(fields=['category', 'status'], name='groups_grou_categor_1bf78b_idx'),
        ),
        migrations.AddIndex(
            model_name='grouplisting',
            index=models.Index(fields=['group_id'], name='groups_grou_group_i_4fb868_idx'),
        ),
        migrations.AddIndex(
            model_name='grouplisting',
            index=models.Index(fields=['-created_at'], name='groups_grou_created_2f2357_idx'),
        ),
    ]
