# Generated by Django 4.2.24 on 2025-09-11 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ESCROW_CREATED', 'Escrow Created'), ('PAYMENT_RECEIVED', 'Payment Received'), ('TRANSFER_STARTED', 'Transfer Started'), ('OWNERSHIP_CHANGED', 'Ownership Changed'), ('VERIFICATION_PASSED', 'Verification Passed'), ('VERIFICATION_FAILED', 'Verification Failed'), ('FUNDS_RELEASED', 'Funds Released'), ('FUNDS_REFUNDED', 'Funds Refunded'), ('DISPUTE_OPENED', 'Dispute Opened'), ('DISPUTE_RESOLVED', 'Dispute Resolved')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED_SELLER', 'Resolved - Favor Seller'), ('RESOLVED_BUYER', 'Resolved - Favor Buyer'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(choices=[('USDT', 'USDT (Tether)'), ('ETH', 'Ethereum'), ('BTC', 'Bitcoin')], max_length=10)),
                ('usd_equivalent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('FUNDED', 'Escrow Funded'), ('AWAITING_TRANSFER', 'Awaiting Group Transfer'), ('VERIFYING', 'Verifying Transfer'), ('COMPLETED', 'Transfer Completed'), ('REFUNDED', 'Refunded to Buyer'), ('DISPUTED', 'Under Dispute'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_address', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_deadline', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='escrow.escrowtransaction')),
            ],
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='escrow.telegramuser'),
        ),
    ]
