# Generated by Django 4.2.24 on 2025-09-11 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='group_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grouplisting'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='escrow.telegramuser'),
        ),
        migrations.AddField(
            model_name='disputecase',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrow.telegramuser'),
        ),
        migrations.AddField(
            model_name='disputecase',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputecase',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='escrow.escrowtransaction'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escrow.telegramuser'),
        ),
    ]
