# Generated by Django 4.2.24 on 2025-09-19 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escrow', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputecase',
            name='arbitrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitrated_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputecase',
            name='evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Links to screenshots, message IDs, etc.'),
        ),
        migrations.AddField(
            model_name='disputecase',
            name='ruling',
            field=models.CharField(blank=True, choices=[('FAVOR_SELLER', 'Favor Seller - Release Funds'), ('FAVOR_BUYER', 'Favor Buyer - Refund'), ('PARTIAL_REFUND', 'Partial Refund'), ('NO_ACTION', 'No Action')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disputecase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('AWAITING_RULING', 'Awaiting Ruling'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='disputecase',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_case', to='escrow.escrowtransaction'),
        ),
    ]
