# Generated by Django 4.2.24 on 2025-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_disputecase_arbitrator_disputecase_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='payment_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='payment_charge_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
